[package]
name = "rust-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webbrowser = "0.5.5"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
